# Generated by Django 4.2.2 on 2023-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_purchesdetails_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchesdetails',
            name='product_code',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
