# Generated by Django 4.2.2 on 2023-08-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_purchesdetails_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchesdetails',
            name='PurchesTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
